import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

export type CompanyDocument = HydratedDocument<Company>;

/**
 * Mongoose Schema for Portfolio Companies.
 *
 * Design Decisions:
 * - `contentHash`: Hidden by default (`select: false`) to reduce payload size. Used for Optimistic Concurrency Control.
 * - `aiAnalysis`: Stored as an embedded object to avoid expensive $lookup joins (NoSQL Best Practice).
 * - `name`: Indexed and Unique to serve as the idempotent key.
 */
@Schema({ timestamps: true })
export class Company {
  @Prop({ required: true, unique: true, index: true })
  name: string;

  @Prop()
  industry: string;

  @Prop()
  assetClass: string;

  @Prop()
  region: string;

  @Prop()
  hqLocation: string;

  @Prop()
  description: string;

  @Prop()
  website: string;

  @Prop()
  yearOfInvestment: number;

  @Prop()
  logoUrl: string;

  // Embedded Object: External Metadata from the Spider Service
  @Prop({ type: Object })
  websiteData?: {
    title?: string;
    metaDescription?: string;
    isAlive: boolean;
    lastCheckedAt: Date;
  };

  // Embedded Object: Intelligence generated by the Enrichment Service (LLM/Regex)
  @Prop({ type: Object })
  aiAnalysis?: {
    summary?: string;
    tags?: string[];
  };

  // Optimization: A hash of the business data. Used to detect changes without field-by-field comparison.
  @Prop({ select: false })
  contentHash: string;

  @Prop({ default: Date.now })
  scrapedAt: Date;
}

export const CompanySchema = SchemaFactory.createForClass(Company);
